// What the block at the bottom of the main screen shows (G76, docs/165): one state of a passenger or
// a driver, counted when it comes to see where people stand and what they wait for (docs/29).
export const DOCK_STATES = [
  'idle',
  'favorite',
  'request',
  'offers',
  'asked',
  'confirmed',
  'moved',
  'meeting',
  'driverWaits',
  'onRoad',
  'arrivedAsk',
  'noShow',
  'ended',
  'refused',
  'draft',
  'pending',
  'fix',
  'welcome',
  'low',
  'short',
  'published',
  'requests',
  'accepted',
  'depart',
  'departAsk',
  'passengerWaits',
  'atPoint',
] as const;
