import type { ApiClients } from './context/api-clients';
import { NOT_USED } from './test-not-used';

// Tests of the driver and the team screens replace only the calls they need.
type Overrides = { readonly [Name in keyof ApiClients]?: Partial<ApiClients[Name]> };
export const testClients = (overrides: Overrides): ApiClients => ({
  drivers: {
    getApplication: NOT_USED,
    uploadPhoto: NOT_USED,
    submit: NOT_USED,
    getPhoto: NOT_USED,
    ...overrides.drivers,
  },
  moderation: {
    // A team member without a name in the test: the card waits (G53).
    me: NOT_USED,
    queue: NOT_USED,
    get: NOT_USED,
    photo: NOT_USED,
    decide: NOT_USED,
    block: NOT_USED,
    blocks: NOT_USED,
    unblock: NOT_USED,
    faces: NOT_USED,
    facePhoto: NOT_USED,
    decideFace: NOT_USED,
    ...overrides.moderation,
  },
  market: {
    recommend: NOT_USED,
    searchTrips: NOT_USED,
    trip: NOT_USED,
    directions: NOT_USED,
    tripDays: NOT_USED,
    myTrips: NOT_USED,
    publishTrip: NOT_USED,
    schedule: async () => ({ windows: [], full: false }),
    cancelTrip: NOT_USED,
    retimeTrip: NOT_USED,
    lowerTripPrice: NOT_USED,
    departTrip: NOT_USED,
    arriveTrip: NOT_USED,
    searchRequests: NOT_USED,
    myRequests: NOT_USED,
    publishRequest: NOT_USED,
    cancelRequest: NOT_USED,
    setRequestCalls: NOT_USED,
    requestBoard: NOT_USED,
    openTrip: NOT_USED,
    month: NOT_USED,
    teamTrips: NOT_USED,
    ...overrides.market,
  },
  pricing: {
    state: NOT_USED,
    preview: NOT_USED,
    save: NOT_USED,
    rollback: NOT_USED,
    directions: NOT_USED,
    setDirection: NOT_USED,
    ...overrides.pricing,
  },
  channels: {
    list: NOT_USED,
    save: NOT_USED,
    remove: NOT_USED,
    tripPublicity: NOT_USED,
    tripViewed: NOT_USED,
    ...overrides.channels,
  },
  bookings: {
    book: NOT_USED,
    myBookings: NOT_USED,
    cancelMine: NOT_USED,
    driverBookings: NOT_USED,
    answer: NOT_USED,
    meet: NOT_USED,
    tripBookings: NOT_USED,
    sendOffer: NOT_USED,
    // No offer sent yet: the board of requests asks for them (G41, docs/90 F-D1).
    driverOffers: async () => [],
    myOffers: NOT_USED,
    answerOffer: NOT_USED,
    openTalk: NOT_USED,
    offerSalonTrip: NOT_USED,
    ...overrides.bookings,
  },
  wallet: { mine: NOT_USED, all: NOT_USED, of: NOT_USED, adjust: NOT_USED, ...overrides.wallet },
  chat: {
    socketUrl: NOT_USED,
    about: async () => ({ booking: null, role: null, request: null, offer: null, driver: null }),
    share: NOT_USED,
    stopSharing: NOT_USED,
    shareTrip: NOT_USED,
    putTripStory: NOT_USED,
    stopTripSharing: NOT_USED,
    came: NOT_USED,
    boarded: NOT_USED,
    arrived: NOT_USED,
    sharedTrip: NOT_USED,
    follow: NOT_USED,
    ...overrides.chat,
  },
  subscriptions: {
    mine: NOT_USED,
    subscribe: NOT_USED,
    remove: NOT_USED,
    renew: NOT_USED,
    ...overrides.subscriptions,
  },
  feedback: {
    target: NOT_USED,
    review: NOT_USED,
    reviewsOf: NOT_USED,
    complain: NOT_USED,
    queue: NOT_USED,
    complaint: NOT_USED,
    chat: NOT_USED,
    decide: NOT_USED,
    answerRefund: NOT_USED,
    ...overrides.feedback,
  },
  stats: { get: NOT_USED, ...overrides.stats },
  calls: { ice: NOT_USED, connect: NOT_USED, pull: NOT_USED, renegotiate: NOT_USED, ...overrides.calls },
  comfort: { favorites: NOT_USED, save: NOT_USED, forget: NOT_USED, history: NOT_USED, ...overrides.comfort },
  map: {
    archiveUrl: 'https://api.test/map/archive.pmtiles',
    fontsUrl: 'https://api.test/map/fonts/{fontstack}/{range}.pbf',
    search: NOT_USED,
    where: NOT_USED,
    near: async () => [],
    border: NOT_USED,
    pitakOf: NOT_USED,
    ...overrides.map,
  },
  pitaks: {
    all: NOT_USED,
    add: NOT_USED,
    change: NOT_USED,
    direction: NOT_USED,
    history: NOT_USED,
    ...overrides.pitaks,
  },
  company: { current: NOT_USED, state: NOT_USED, save: NOT_USED, ...overrides.company },
  sounds: { current: NOT_USED, state: NOT_USED, pick: NOT_USED, ...overrides.sounds },
});
