import type { ApiClients } from './context/api-clients';
import { NOT_USED } from './test-not-used';

export type Overrides = { readonly [Name in keyof ApiClients]?: Partial<ApiClients[Name]> };

// The second half of testClients (test-clients.ts): one file stays under 150 lines.
export const otherClients = (overrides: Overrides) => ({
  chat: {
    socketUrl: NOT_USED,
    about: async () => ({ booking: null, role: null, request: null, offer: null, driver: null }),
    // No unread chats: the sheet «Yangi xabar» stays away unless a test brings one (G68).
    unread: async () => [],
    answer: NOT_USED,
    share: NOT_USED,
    stopSharing: NOT_USED,
    shareTrip: NOT_USED,
    putTripStory: NOT_USED,
    stopTripSharing: NOT_USED,
    came: NOT_USED,
    boarded: NOT_USED,
    arrived: NOT_USED,
    sharedTrip: NOT_USED,
    follow: NOT_USED,
    ...overrides.chat,
  },
  subscriptions: {
    mine: NOT_USED,
    subscribe: NOT_USED,
    remove: NOT_USED,
    renew: NOT_USED,
    ...overrides.subscriptions,
  },
  feedback: {
    target: NOT_USED,
    review: NOT_USED,
    reviewsOf: NOT_USED,
    complain: NOT_USED,
    notes: NOT_USED,
    queue: NOT_USED,
    complaint: NOT_USED,
    chat: NOT_USED,
    decide: NOT_USED,
    answerRefund: NOT_USED,
    ...overrides.feedback,
  },
  stats: { get: NOT_USED, ...overrides.stats },
  calls: { ice: NOT_USED, connect: NOT_USED, pull: NOT_USED, renegotiate: NOT_USED, ...overrides.calls },
  comfort: {
    favorites: NOT_USED,
    save: NOT_USED,
    forget: NOT_USED,
    history: NOT_USED,
    standing: NOT_USED,
    ...overrides.comfort,
  },
  map: {
    archiveUrl: 'https://api.test/map/archive.pmtiles',
    fontsUrl: 'https://api.test/map/fonts/{fontstack}/{range}.pbf',
    search: NOT_USED,
    where: NOT_USED,
    near: async () => [],
    border: NOT_USED,
    pitakOf: NOT_USED,
    ...overrides.map,
  },
  pitaks: {
    all: NOT_USED,
    add: NOT_USED,
    change: NOT_USED,
    direction: NOT_USED,
    history: NOT_USED,
    ...overrides.pitaks,
  },
  company: { current: NOT_USED, state: NOT_USED, save: NOT_USED, ...overrides.company },
  sounds: { current: NOT_USED, state: NOT_USED, pick: NOT_USED, ...overrides.sounds },
  // The brand defaults: the owner changed nothing unless a test says so (G75).
  limits: { current: async () => ({ values: {} }), state: NOT_USED, change: NOT_USED, ...overrides.limits },
  team: {
    navbat: NOT_USED,
    take: async () => undefined,
    attention: NOT_USED,
    work: NOT_USED,
    journal: NOT_USED,
    members: NOT_USED,
    add: NOT_USED,
    person: NOT_USED,
    channelHealth: NOT_USED,
    avatar: NOT_USED,
    support: NOT_USED,
    answer: NOT_USED,
    remove: NOT_USED,
    ...overrides.team,
  },
});
