// Digits written as words (docs/07): Uzbek (Latin and Cyrillic) and Russian. A long run of them
// is a phone number, a short one ("bir joy", "ikki kishi") is normal speech.
const UZBEK = [
  'nol',
  'bir',
  'ikki',
  'uch',
  'tort',
  'besh',
  'olti',
  'yetti',
  'sakkiz',
  'toqqiz',
  'on',
  'yigirma',
  'ottiz',
  'qirq',
  'ellik',
  'oltmish',
  'yetmish',
  'sakson',
  'toqson',
  'yuz',
];
const UZBEK_CYRILLIC = [
  'нол',
  'бир',
  'икки',
  'уч',
  'тўрт',
  'беш',
  'олти',
  'етти',
  'саккиз',
  'тўққиз',
  'ўн',
  'йигирма',
  'ўттиз',
  'қирқ',
  'эллик',
  'олтмиш',
  'етмиш',
  'саксон',
  'тўқсон',
  'юз',
];
const RUSSIAN = [
  'ноль',
  'нуль',
  'один',
  'одна',
  'два',
  'две',
  'три',
  'четыре',
  'пять',
  'шесть',
  'семь',
  'восемь',
  'девять',
  'десять',
  'двадцать',
  'тридцать',
  'сорок',
  'пятьдесят',
  'шестьдесят',
  'семьдесят',
  'восемьдесят',
  'девяносто',
  'сто',
];

// Apostrophes (oʻ, to'rt) are dropped before the lookup: "toʻrt" and "to'rt" are one word.
export const NUMBER_WORDS: ReadonlySet<string> = new Set([...UZBEK, ...UZBEK_CYRILLIC, ...RUSSIAN]);
