import { checkRoute, type Location } from '@platform/contracts';
import { roadFactor, roadKm, type RoadFactors } from '../domain/distance';

// Builds migrations/0003_locations.sql from seed/*.json (pnpm locations:seed, docs/48).
// Pure: the same seed always gives the same SQL, a test checks the migration is up to date.
export type SeedPlace = Location & { readonly position: number };

const LOCALE = 'uz-Latn';
// D1 limits one statement to 100 KB: rows go in small groups.
const ROWS_PER_INSERT = 400;

const text = (value: string) => `'${value.replaceAll("'", "''")}'`;

function inserts(table: string, columns: string, rows: readonly string[]): string[] {
  const statements: string[] = [];
  for (let start = 0; start < rows.length; start += ROWS_PER_INSERT) {
    const values = rows.slice(start, start + ROWS_PER_INSERT).join(',\n');
    statements.push(`INSERT INTO ${table} (${columns}) VALUES\n${values};`);
  }
  return statements;
}

// Every pair of level 2 places where a trip is possible, stored once (from < to).
export function seedDistances(places: readonly SeedPlace[], factors: RoadFactors) {
  const byId = new Map(places.map((place) => [place.id, place]));
  const level2 = places.filter((place) => place.parentId !== null).sort((a, b) => (a.id < b.id ? -1 : 1));
  const pairs: { from: string; to: string; km: number }[] = [];
  level2.forEach((a, index) => {
    for (const b of level2.slice(index + 1)) {
      if (checkRoute(a, b, (id) => byId.get(id)) !== null) continue;
      const factor = roadFactor(factors, a.parentId ?? a.id, b.parentId ?? b.id);
      pairs.push({ from: a.id, to: b.id, km: roadKm(a, b, factor) });
    }
  });
  return pairs;
}

const SCHEMA = `-- G05: regions, districts, cities (docs/14, docs/48). Generated by pnpm locations:seed, do not edit.
CREATE TABLE locations (
  id TEXT PRIMARY KEY,
  parent_id TEXT REFERENCES locations (id),
  type TEXT NOT NULL CHECK (type IN ('region', 'district', 'city')),
  lat REAL NOT NULL,
  lng REAL NOT NULL,
  one_city INTEGER NOT NULL DEFAULT 0,
  position INTEGER NOT NULL DEFAULT 0,
  updated_at INTEGER NOT NULL
);
CREATE INDEX locations_parent ON locations (parent_id);

CREATE TABLE location_translations (
  location_id TEXT NOT NULL REFERENCES locations (id),
  locale TEXT NOT NULL,
  name TEXT NOT NULL,
  PRIMARY KEY (location_id, locale)
);

-- Road km between level 2 places; source 'team' marks a distance corrected by the team.
CREATE TABLE location_distances (
  from_id TEXT NOT NULL REFERENCES locations (id),
  to_id TEXT NOT NULL REFERENCES locations (id),
  km INTEGER NOT NULL CHECK (km > 0),
  source TEXT NOT NULL CHECK (source IN ('formula', 'team')),
  updated_at INTEGER NOT NULL,
  PRIMARY KEY (from_id, to_id),
  CHECK (from_id < to_id)
);`;

export function buildSeedSql(places: readonly SeedPlace[], factors: RoadFactors, stamp: number): string {
  // Regions first: districts refer to them.
  const ordered = [...places].sort((a, b) => Number(a.parentId !== null) - Number(b.parentId !== null));
  const locationRows = ordered.map(
    (place) =>
      `(${text(place.id)}, ${place.parentId === null ? 'NULL' : text(place.parentId)}, ${text(place.type)}, ` +
      `${place.lat}, ${place.lng}, ${Number(place.oneCity)}, ${place.position}, ${stamp})`,
  );
  const nameRows = ordered.map((place) => `(${text(place.id)}, ${text(LOCALE)}, ${text(place.name)})`);
  const distanceRows = seedDistances(places, factors).map(
    ({ from, to, km }) => `(${text(from)}, ${text(to)}, ${km}, 'formula', ${stamp})`,
  );
  return (
    [
      SCHEMA,
      ...inserts('locations', 'id, parent_id, type, lat, lng, one_city, position, updated_at', locationRows),
      ...inserts('location_translations', 'location_id, locale, name', nameRows),
      ...inserts('location_distances', 'from_id, to_id, km, source, updated_at', distanceRows),
    ].join('\n\n') + '\n'
  );
}
